### ISSUE TITLE
graphics_interop

### ISSUE THREAD

**Issue by ShapelessGolem** [Sorenon/sorenon_openxr_layer#2]
When I compile i get this error. any fix?

```
error[E0308]: mismatched types
  --> graphics_interop\src\apis\vulkan.rs:83:13
   |
83 |             khr_external_memory,
   |             ^^^^^^^^^^^^^^^^^^^ expected struct `KhrExternalMemoryWin32Fn`, found `()`

```

**Comment by Sorenon** [comment]
Should be fixed now

Out of interest why are you trying to build this for windows?

**Comment by ShapelessGolem** [comment]
> Should be fixed now
> 
> Out of interest why are you trying to build this for windows?

it's silly, fabric minecraft vr. not too sure what i'm doing honestly.
